#!/bin/bash

ln -s -f ~/dotfiles/.vim ~
ln -s -f ~/dotfiles/.vimrc ~/.vimrc
ln -s -f ~/dotfiles/.gitconfig ~/.gitconfig
ln -s -f ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -s -f ~/dotfiles/.zshrc ~/.zshrc
git config --global core.excludesfile ~/.gitignore_global
cd ~/dotfiles
git submodule update --init
